const Router = require('express')
const router = new Router()
const productController = require('../contollers/productController')
const {isAuthorized} = require("../middleware/authMiddleware");


router.post('/create', productController.createProduct)
router.put('/updateDescription', productController.updateDescription)
router.post('/attachPhoto', productController.attachPhoto)
router.delete('/deletePhoto', productController.deletePhoto)
router.post('/addInBasket', isAuthorized, productController.addInBasket)
router.delete('/deleteInBasket', isAuthorized, productController.deleteInBasket)
router.delete('/deleteAllInBasket', isAuthorized, productController.deleteAllInBasket)
router.get('/getBasket', isAuthorized, productController.getBasket)
router.get('/getAll', isAuthorized, productController.getAll)
router.get('/getOneProduct/:vendor_code', isAuthorized, productController.getOneProduct)
router.get('/getAllProducts', productController.getAllAnon)
router.put('/updateCountBasket', isAuthorized, productController.updateCountBasket)
router.put('/updatePriceBasketItem', isAuthorized, productController.updatePriceBasketItem)
router.post('/sendExcel', isAuthorized, productController.sendExcel)
router.get('/getOrders', isAuthorized, productController.getOrders)
router.get('/getOrderList/:id', isAuthorized, productController.getOrderList)
router.post('/copyOrder', isAuthorized, productController.copyOrder)
router.put('/updatePrice', isAuthorized, productController.updatePrice)
router.get('/getProductPrices', isAuthorized, productController.getProductPrices)
router.get('/getSimilarProduct/:vendor_code', productController.getSimilarProduct)
router.post('/checkExcel', productController.checkExcel)
router.post('/fillOutBasket', isAuthorized, productController.fillOutBasket)

module.exports = router